import random

colors = [
    "alice blue",
    "antique white",
    "aquamarine",
    "azure",
    "beige",
    "bisque",
    "black",
    "blanched almond",
    "blue",
    "blue violet",
    "brown",
    "burlywood",
    "cadet blue",
    "chartreuse",
    "chocolate",
    "coral",
    "cornflower blue",
    "cornsilk",
    "crimson",
    "cyan",
    "dark blue",
    "dark cyan",
    "dark goldenrod",
    "dark gray",
    "dark green",
    "dark khaki",
    "dark magenta",
    "dark olive green",
    "dark orange",
    "dark orchid",
    "dark red",
    "dark salmon",
    "dark sea green",
    "dark slate blue",
    "dark slate gray",
    "dark turquoise",
    "dark violet",
    "deep pink",
    "deep sky blue",
    "dim gray",
    "dodger blue",
    "firebrick",
    "floral white",
    "forest green",
    "gainsboro",
    "ghost white",
    "gold",
    "goldenrod",
    "gray",
    "green",
    "green yellow",
    "honeydew",
    "hot pink",
    "indian red",
    "indigo",
    "ivory",
    "khaki",
    "lavender",
    "lavender blush",
    "lawn green",
    "lemon chiffon",
    "light blue",
    "light coral",
    "light cyan",
    "light goldenrod yellow",
    "light gray",
    "light green",
    "light pink",
    "light salmon",
    "moccasin",
    "navajo white",
    "navy",
    "old lace",
    "olive",
    "olive drab",
    "orange",
    "orange red",
    "orchid",
    "pale goldenrod",
    "pale green",
    "pale turquoise",
    "pale violet red",
    "papaya whip",
    "peach puff",
    "peru",
    "pink",
    "plum",
    "powder blue",
    "purple",
    "red",
    "rosy brown",
    "royal blue",
    "saddle brown",
    "salmon",
    "sandy brown",
    "sea green",
    "seashell",
    "sienna",
    "sky blue",
    "slate blue",
    "slate gray",
    "snow",
    "spring green",
    "steel blue",
    "tan",
    "thistle",
    "tomato",
    "turquoise",
    "violet",
    "wheat",
    "white",
    "white smoke",
    "yellow",
    "yellow green"
]



def random_color():
    return random.choice(colors)